/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'homemadeFood' : null } |
  { 'freshVegetables' : null } |
  { 'spices' : null };
export interface MenuItem {
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : Category,
  'price' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPersistentMenuItem' : ActorMethod<[MenuItem], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePersistentMenuItem' : ActorMethod<[bigint], undefined>,
  'getAllPersistentMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllPersistentMenuItemsByCategory' : ActorMethod<
    [],
    Array<[Category, Array<MenuItem>]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPersistentMenuItem' : ActorMethod<[bigint], MenuItem>,
  'getPersistentMenuItemsByCategory' : ActorMethod<[Category], Array<MenuItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleItems' : ActorMethod<[], undefined>,
  'updatePersistentMenuItem' : ActorMethod<[bigint, MenuItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];