/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'specialPerKg' : IDL.Null,
  'gymProtein' : IDL.Null,
  'monthlyFood' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : Category,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPersistentMenuItem' : IDL.Func([MenuItem], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePersistentMenuItem' : IDL.Func([IDL.Nat], [], []),
  'getAllPersistentMenuItems' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, MenuItem))],
      ['query'],
    ),
  'getAllPersistentMenuItemsByCategory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Category, IDL.Vec(IDL.Tuple(IDL.Nat, MenuItem))))],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPersistentMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
  'getPersistentMenuItemsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'seedSampleItems' : IDL.Func([], [], []),
  'updatePersistentMenuItem' : IDL.Func([IDL.Nat, MenuItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'specialPerKg' : IDL.Null,
    'gymProtein' : IDL.Null,
    'monthlyFood' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPersistentMenuItem' : IDL.Func([MenuItem], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePersistentMenuItem' : IDL.Func([IDL.Nat], [], []),
    'getAllPersistentMenuItems' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, MenuItem))],
        ['query'],
      ),
    'getAllPersistentMenuItemsByCategory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Category, IDL.Vec(IDL.Tuple(IDL.Nat, MenuItem))))],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPersistentMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
    'getPersistentMenuItemsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'seedSampleItems' : IDL.Func([], [], []),
    'updatePersistentMenuItem' : IDL.Func([IDL.Nat, MenuItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };